# version: '3.9'
services:
  postgres:
    image: postgres:latest
    volumes:
      - /home/kun/projects/dbs/fiskal:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
        - .env
    networks:
      pgnet:
        ipv4_address: 172.18.0.3
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    env_file:
        - .env
    ports:
      - "5050:80"
    networks:
      pgnet:
        ipv4_address: 172.18.0.2
networks:
  pgnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24