# version: '3.9'
services:
  postgres:
    image: postgres:latest
    volumes:
      - /home/kun/projects/dbs/fiskal:/var/lib/postgresql/data
    ports:
      - 5432:5432
    # environment:
    #   POSTGRES_USER: postgres
    #   POSTGRES_PASSWORD: postgres
    env_file:
        - .env

